AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

require: rubocop-rspec
